<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Beauto OTP </title>
</head>
<body>

<div>Your One Time Password(OTP)  is <b>${user}</b></div>
<br/>
<div> Have a nice day..!</div>
</body>
</html>